### ISSUE TITLE
Please make a new release, fxing the deprecated warnings from simple_form

### ISSUE THREAD

**Issue by eiked** [bigtunacan/rails-jquery-autocomplete#12]
I'm now using the head version.
This does fix the deprecated warnings from simple_form for me.
And it seems to work just fine for me.

I'd like to suggest that you release that new version as 1.1.0
(because this really is a big fix for all of us)

Thanks for the improvements.
I believe there is much more to come.

Looks like this is now the premiere gem for handling autocomplete.

I patched it way back to also deliver images links and such.

As a last note, you might even consider to do away with the dependecies on jquery.
Like making this the rails autocomplete gem.

~eike

**Comment by eiked** [comment]
Just fishing:
% man tunefs
No manual entry for tunefs
oops?

FreeBSD to the rescue:
     You can tune a file system, but you cannot tune a fish.
(like cat for a fish)

**Comment by bigtunacan** [comment]
@eiked I am planning to put out a new release soon.  I have some other updates planned, I may do some smaller 1.0.x releases in between which would include the simple_form update.  The largest change is that I intend  to decouple the the ORM layers from the primary codebase.  Right now ActiveRecord, MongoMapper, and Mongoid are all baked in.  This is problematic since anytime there is a change is must be applied to each ORM and slows the overall progress of the gem.  

It also makes it more difficult should someone want to add support for an alternative datastore.

While there may be value in removing the dependency on jQuery, that isn't on my radar yet.
