### ISSUE TITLE
does :scopes support parameter input?

### ISSUE THREAD

**Issue by Aiken00** [bigtunacan/rails-jquery-autocomplete#41]
Thank you for creating such useful gem.

And I would like to ask if I write something like that in my model.
scope : with_certain_state, ->(state) { where(:state => state) }

Is it possible to use it with the help of scopes in autocomplete?

**Comment by bigtunacan** [comment]
@Aiken00 For this you would be better off redefining the get_autocomplete_items method in your controller class.  I'm going to point you this Stack Overflow since this question is answered in more detail there.

http://stackoverflow.com/questions/7244515/rails-gem-rails3-jquery-autocomplete-how-to-scope-by-user
